# Generated by Django 2.1 on 2018-08-30 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_lists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Tribunais',
            new_name='courts',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Processos',
            new_name='processes',
        ),
    ]
